### ISSUE TITLE
Winetricks unable to install corefonts - quotation marks missing somewhere

### ISSUE THREAD

**Issue by grizeldi** [lutris/lutris#1006]
I'm writing an installer, which currently looks like this:
```
name: Planetbase
game_slug: planetbase
version: Planetbase Winesteam Installer
slug: planetbase_winesteam_installer
runner: winesteam

script:
    game:
        appid: 403190
        prefix: $GAMEDIR/prefix
        arch: win64
        
    installer:
    - task:
        description: Setting up wine prefix
        name: create_prefix
        prefix: $GAMEDIR/prefix
        arch: win64
        install_mono: true
    - task:
        description: Setting windows version to windows 7
        name: winetricks
        prefix: $GAMEDIR/prefix
        app: win7
    - task:
        description: Installing mscorefonts
        name: winetricks
        prefix: $GAMEDIR/prefix
        app: corefonts
        
    winesteam:
        UseGLSL: disabled
        dxvk: true
        dxvk_version: '0.63'
        version: staging-3.12-x86_64
```
When attempting to install it though, installation of corefonts fails. I assume it's because there are missing quotation marks around the path lutris provides to winetricks so it gets cut off at the space in "Program Files".
Output of the corefonts installation task:
```
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20180513-next - sha256sum: e4b2f5e8703247ea422b9094293a754339fd63c890a82b777fb9dbb6b6b369b0 with wine-3.12 (Staging) and WINEARCH=win64
------------------------------------------------------
You are running winetricks-20180513-next, latest upstream is winetricks-20180603!
------------------------------------------------------
------------------------------------------------------
You should update using your distribution's package manager, --self-update, or manually.
------------------------------------------------------
Executing w_do_call corefonts
Executing load_corefonts 
Executing cabextract -q -d /home/grizeldi/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program Files/Steam/steamapps/common/Planetbase/prefix/dosdevices/c:/windows/temp/_corefonts /home/grizeldi/.cache/winetricks/corefonts/arial32.exe
Executing cp -f /home/grizeldi/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program /home/grizeldi/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program Files/Steam/steamapps/common/Planetbase/prefix/dosdevices/c:/windows/Fonts/program
cp: cannot stat '/home/grizeldi/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program': No such file or directory
------------------------------------------------------
```
Shouldn't be too hard to fix I believe.
