### ISSUE TITLE
Introduce fail message for the installation process

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1122]
To avoid stuff like #1121, at least with Wine installers, Lutris should check if the game executable exists after the installer finished and if it doesn’t, show a fail message (instead of a success like it is now).

**Comment by Kreyren** [comment]
Agreed, but i can't imagine an effective way of implementing such feature since every installer is different.

**Comment by duhow** [comment]
Lets say...
```yaml
- task:
    name: wineexec
    prefix: $GAMEDIR
    executable: $installer
- expect:
    file: "$GAMEDIR/Program Files/Game/game.exe"
    status: exists
- expect:
    regkey: "HKLM/....."
    status: exists
```
