### ISSUE TITLE
Installer for Star Wars: Rogue Squadron

### ISSUE THREAD

**Issue by medfreeman** [lutris/lutris#114]
_Xod edit: for ref, the game is [here](https://lutris.net/games/star-wars-rogue-squadron/)_

Hi,

is there actually a way to download a custom wine version (let's say with specific patches for a game to work) and copy it to the right folder, then telling lutris to use this specific version for the game ?

ie:

```
runner: wine
game:
  prefix: $GAMEDIR
  version: custom
files:
- game-installer: http://site.com/gamesetup.exe
- wine-archive: http://site.com/wine-custom.tar.gz
installer:
- task:
- extract:
    file: wine-archive
    dst: $WINEDIR/
- task:
    name: wineexec
    executable: game-installer
    prefix: $GAMEDIR
    description: Installing Game
```
