### ISSUE TITLE
Installer documentation examples have errors

### ISSUE THREAD

**Issue by Kirtai** [lutris/lutris#1166]
In the [installers](https://github.com/lutris/lutris/blob/master/docs/installers.rst) documentation, both of the GOG examples have errors in them.

The first one (for mojosetup games) is missing indentation after "- execute:" and also uses "executable:" instead of "file:" in that stanza.
e.g. I had to use the following to get a working installer
```
  installer:
  - chmodx: installer 
  - execute:
      file: installer
      description: Installing game, it may take a while...
      args: -- --i-agree-to-all-licenses --noreadme --nooptions --noprompt --destination=$GAMEDIR
```

The second GOG example (using unzip) also appears to be missing one layer of indentation for the "- execute:" stanza.

**Comment by RobLoach** [comment]
Usign `executable:` is for `task`... ala...

```

  installer:
  - task:
    executable: installer
    name: wineexec
    prefix: $GAMEDIR/prefix
    arch: win64
```
