### ISSUE TITLE
[glitch] Installers scripts registered with "game" section first.

### ISSUE THREAD

**Issue by Bumbadawg** [lutris/lutris#1269]
Let me take this AoE3 installer script as an example:

```
installer:
- input_menu:
    description: 'Select how much VRAM (GPU memory) Age of Empires III will allocate:'
    id: MEM
    options:
    - '256': 256MB
    - '512': 512MB
    - '1024': 1024MB
    - '2048': 2048MB
    - '4096': 4096MB
    preselect: '1024'
- task:
    app: corefonts l3codecx mfc42
    arch: win32
    description: Working around missing libs.
    name: winetricks
- task:
    app: winxp
    description: Setting Windows version to XP
    name: winetricks
system:
  env:
    PBA_ENABLE: '1'
    __PBA_GEO_HEAP: $INPUT_MEM
**game:
  appid: 105450
  arch: win32
  args: +noIntroCinematics**
winesteam:
  esync: 'true'
  overrides:
    xaudio2_7: native,builtin
  version: tkg-3.19-x86_64
```
As you can clearly see, _game_ section is after _installer_ one. But when saving the draft on the website, the yaml restores the _game_ section first.

My problem: the game installs first on Steam, whatever the System configuration (WinXP in my case).
So when launching an install:

1. installer downloads WineSteam (defaulting to Win7),
2. installer then downloads the game
3. installer then proposes my _input-list_ to finish configuration
4. installer sets WineSteam to WinXP
5. i launch the game and it redownloads Steam WinXP version..

My need:
i want the installer to perform the WinXP/winetricks task first to avoid redownloading Steam twice.
Is it possible or is the yaml/json node order messing it up..
Or might it be the parsing ?
