### ISSUE TITLE
Strong checksums for installer files

### ISSUE THREAD

**Issue by sorsasampo** [lutris/lutris#1383]
Allow providing optional checksum for `files:`.

Python `hashlib`'s [`new(algo)`](https://docs.python.org/3/library/hashlib.html#hashlib.new) function could be leveraged here to support all existing and future checksum algorithms.

Example:

```
files:
- file1:
    url: https://vendor.com/installer-that-should-not-change-v1.0.exe
    checksum: sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```
