### ISSUE TITLE
[next] Process monitor doesn't catch executables that exit too fast

### ISSUE THREAD

**Issue by daniel-j** [lutris/lutris#1491]
An easy way to test this is with the following installer script:
```yaml
name: test
slug: test-test
version: test
game_slug: test
runner: linux

script:
  installer:
  - execute: 'true'
```
The process `true` exits immediately, causing the install to never continue. The process monitor seems to wait for the process to start, which already have happened, so it will wait a long time (forever?) This would also apply to other fast executables in tasks or other monitored processes.
