### ISSUE TITLE
set_registry_key doesn't support REG_DWORD

### ISSUE THREAD

**Issue by TomBZombie** [lutris/lutris#1554]
I thought it would be trivial to add the  `SampleCount` option to force MSAA:

```diff
diff --git a/lutris/runners/wine.py b/lutris/runners/wine.py
index f43e8580..83d8744f 100644
--- a/lutris/runners/wine.py
+++ b/lutris/runners/wine.py
@@ -102,6 +102,7 @@ class wine(Runner):
         "MouseWarpOverride": r"%s/DirectInput" % reg_prefix,
         "OffscreenRenderingMode": r"%s/Direct3D" % reg_prefix,
         "StrictDrawOrdering": r"%s/Direct3D" % reg_prefix,
+        "SampleCount": r"%s/Direct3D" % reg_prefix,
         "Desktop": "MANAGED",
         "WineDesktop": "MANAGED",
         "ShowCrashDialog": "MANAGED",
@@ -358,6 +359,25 @@ class wine(Runner):
                     "writing"
                 )
             },
+            {
+                'option': 'SampleCount',
+                'label': "Anti-aliasing Sample Count",
+                'type': 'choice',
+                'choices': [
+                            ('0', '0 (disabled)'),
+                            ('2', '2'),
+                            ('4', '4'),
+                            ('8', '8'),
+                            ('16', '16')],
+                'default': '0',
+                'advanced': True,
+                'help': (
+                    "Override swapchain sample count. It can be used to force enable multisampling"
+                    "with applications that otherwise don't support it, like the similar control panel setting"
+                    "available with some GPU drivers. This one might work in more cases than the driver setting though."
+                    " Not all applications are compatible with this setting. "
+                   )
+            },
             {
                 'option': 'UseXVidMode',
                 'label': 'Use XVidMode to switch resolutions',
```

However, because SampleCount is a `REG_DWORD` it doesn't work due to `set_registry_key` only being able to create strings as far as I can tell. The same is true of `CSMT` which is why I guess Lutris doesn't have that option either.

**Comment by tannisroot** [comment]
it does support dword:
```
wine / winesteam: set_regedit Modifies the Windows registry. Parameters are path (the registry path, use backslashes), key, value, type (optional value type, default is REG_SZ (string)), prefix (optional WINEPREFIX), arch (optional architecture of the prefix, required when you created win64 prefix).

Example:

- task:
    name: set_regedit
    prefix: $GAMEDIR
    path: HKEY_CURRENT_USER\Software\Valve\Steam
    key: SuppressAutoRun
    value: '00000000'
    type: REG_DWORD
    arch: win64
```
Also, CSMT is enabled by default in newer versions of Wine, so there is no need to manually enable it.
