### ISSUE TITLE
Are installer tasks ordered ?

### ISSUE THREAD

**Issue by Bumbadawg** [lutris/lutris#1738]
Hi @strycore and team,
trying this installer https://lutris.net/games/install/11844/view

The task 
```
- task:
    app: nocrashdialog vcrun2017 win7
```
should be executed before 
```
- task:
    arch: win64
    args: /silent
    description: Installing Origin... Login window may pop-up and close.
    exclude_processes: Origin.exe OriginClientService.exe OriginWebHelperService.exe
      QtWebEngineProcess.exe
    executable: client
    name: wineexec
    prefix: $GAMEDIR
```

BUT, in the facts, i had the prefix set to WinXP. The task winetricks win7 didn't execute, and thus the Origin installer failed complaining it required win7+.

Thanks in advance for your lights.
