### ISSUE TITLE
write_config screwing with dosbox config

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1950]
Editing a config file with the `- write_config` command changes drive names because it thinks it's a key. This causes the game to fail when launching.

```
[autoexec]
@ECHO OFF
mount C "."
mount d "." -t cdrom
c:
cls
SET ARENADATA=C:
d:
ACD -Ssbpdig.adv -IOS220 -IRQS7 -DMAS1 -Mgenmidi.adv -IOM330 -IRQM2 -DMAM1
Exit
```
Becomes:
```
[autoexec]
@ECHO OFF
mount C "."
mount d "." -t cdrom
c=
cls
SET ARENADATA=C:
d=
ACD -Ssbpdig.adv -IOS220 -IRQS7 -DMAS1 -Mgenmidi.adv -IOM330 -IRQM2 -DMAM1
Exit
```
Test installer:
```
name: The Elder Scrolls Arena
game_slug: the-elder-scrolls-arena
version: Freeware 1.07
slug: the-elder-scrolls-arena
runner: dosbox

script:
  files:
  - setup: http://theelderscrolls.wiwiland.net/Fichiers/ArenaSetup.exe
  game:
    config_file: $GAMEDIR/drive_c/Games/Bethesda Softworks/Arena/DosBox.conf
    main_file: $GAMEDIR/drive_c/Games/Bethesda Softworks/Arena/ACD.EXE
  installer:
  - task:
      args: /LANG=en /SP- /SILENT
      description: I don't know how to stop it from opening the browser. Sorry.
      executable: setup
      name: wine.wineexec
  - write_config:
      file: $GAMEDIR/drive_c/Games/Bethesda Softworks/Arena/DosBox.conf
      key: fullscreen
      section: sdl
      value: false
  system: {}
```
