### ISSUE TITLE
Cannot extract to the $CACHE directory if a file has the same name as a file id.

### ISSUE THREAD

**Issue by openglfreak** [lutris/lutris#2004]
Files are downloaded to the cache directory into a subdirectory with the file's id as the name.

Example:
```
exe: Game/start.sh
files:
- game: 'N/A: Please select the GOG.com Linux installer'
- unzip: http://lutris.net/files/tools/unzip.tar.gz
installer:
- extract:
    dst: $CACHE
    file: $unzip
- execute:
    args: $game -d "$GAMEDIR" "data/noarch/*"
    description: Extracting game data, it will take a while...
    file: $CACHE/unzip
- rename:
    dst: $GAMEDIR/Game
    src: $GAMEDIR/data/noarch
```

The extract task fails because there's already a $CACHE/unzip directory, and unzip.tar.gz contains a file named "unzip".
