### ISSUE TITLE
Installer task does not end

### ISSUE THREAD

**Issue by ElectronicManuel** [lutris/lutris#2055]
I'm writing an installer for the [league of legends blitz app](https://blitz.gg).
Here's the [installer](https://github.com/ElectronicManuel/linux-setup/blob/lutris-install/league/blitz-lutris.yml):
```
name: Blitz App League
game_slug: blitz-app-league
version: Installer
slug: blitz-app-league-installer
runner: wine

script:
  requires: league-of-legends
  files:
    - BlitzInstaller:
        url: https://dl.blitz.gg/download/windows
        filename: blitz-installer.exe
    - MonoInstaller: https://dl.winehq.org/wine/wine-mono/4.8.2/wine-mono-4.8.2.msi
  game:
    exe: drive_c/users/$USER/Local\ Settings/Application\ Data/Blitz/Blitz.exe
    prefix: $GAMEDIR
  installer:
    - task:
        name: wineexec
        executable: ""
        prefix: $GAMEDIR
        args: uninstaller --remove '{7290EA95-9F17-58E8-8436-4A532DA0F54E}'
        description: Temporarily removing Wine Mono
    - task:
        name: winetricks
        prefix: $GAMEDIR
        app: dotnet452 win7 corefonts
        description: Installing prerequisites
    - task:
        name: wineexec
        description: Running Blitz app installer
        prefix: $GAMEDIR
        executable: BlitzInstaller
    - task:
        name: winekill
        prefix: $GAMEDIR
    - task:
        name: set_regedit
        prefix: $GAMEDIR
        path: HKEY_CURRENT_USER\Software\Wine\DllOverrides
        key: mscoree
        value: ''
        description: Configuring DLL Overrides
    - task:
        name: set_regedit
        prefix: $GAMEDIR
        path: HKEY_CURRENT_USER\Software\Wine\AppDefaults\Blitz.exe\DllOverrides
        key: mscoree
        value: 'native'
        description: Configuring DLL Overrides for Blitz
    - task:
        name: wineexec
        prefix: $GAMEDIR
        executable: MonoInstaller
        description: Reinstalling Wine Mono
```
Running the installer with wineexec installs the app successfully and opens it in a window.
https://i.imgur.com/oBzv4rs.png
However, lutris stops doing anything after the window opens, only outputting the following and keeping the spinner turning endlessly.
```
014e:fixme:heap:RtlSetHeapInformation 0x230000 0 0x22e390 4 stub
014e:fixme:wer:WerSetFlags (2) stub!
014e:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
014e:err:ole:marshal_object couldn't get IPSFactory buffer for interface {5c6fb596-4828-4ed5-b9dd-293dad736fb5}
014e:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
014e:err:ole:CoMarshalInterface Failed to marshal the interface {5c6fb596-4828-4ed5-b9dd-293dad736fb5}, 80004002
008a:err:rpc:I_RpcReceive we got fault packet with status 0x80004002
001f:fixme:ole:NdrClearOutParameters (0x6ddbe0,0x7faf101680a0,0x6de058): stub
0143:err:ole:dispatch_rpc no apartment found for ipid {ffffffff-ffff-ffff-4e01-00003f010000}
0088:err:rpc:I_RpcReceive we got fault packet with status 0x80010108
001f:fixme:advapi:RegisterEventSourceW ((null),L".NET Runtime Optimization Service"): stub
001f:fixme:advapi:DeregisterEventSource (0xcafe4242) stub
2019-04-17 18:20:33,712: Unable to read stat for process 26212
2019-04-17 18:20:33,712: Unable to read stat for process 26212
2019-04-17 18:20:33,712: Unable to read stat for process 28703
2019-04-17 18:20:33,712: Unable to read stat for process 28703
Waiting on children
```
Lutris still doesn't continue even after I close the window by clicking the system tray button https://i.imgur.com/oS44qar.png.
The only option I have is to cancel.
How do I tell lutris to continue with the installation?
