### ISSUE TITLE
Request: Add Vortex Mod Manager

### ISSUE THREAD

**Issue by Kreyren** [lutris/lutris#2058]
Sharing my results here in case someone wants to make an installer for lutris to make windows game modding easier on linux:
https://github.com/PhoenicisOrg/scripts/issues/903

TLDR: 
- MANDATORY: `dotnet472` workaround.
- MANDATORY: `dxgi.dll` from dxvk.
- Optional: Source with this commit to make native the witcher 2 compatible with modding https://github.com/Nexus-Mods/vortex-games/pull/26

### WIP installer
```yaml
files:
- source: https://github.com/Nexus-Mods/Vortex/releases/download/v0.17.11/vortex-setup-0.17.11.exe
- task:
  app: dotnet472
  description: Installing dotnet472
  name: winetricks
- task:
  app: dxvk
  description: Installing dxvk since dxgi.dll is mandatory
  name: winetricks
wine:
  version: tkg-4.6-x86_64
```

Since i can't contribute with usable installer due tannisroot's freaking out about everything i say + removing my working installers that are supperior to other options (GTA V installer) -> i won't file it myself 

good luck :+1:

**Comment by AccountOneOff** [comment]
Your script is missing the installer section. Tasks/commands must always go under the installer section. You also don't need to install dxvk via winetricks `dxvk: true` does that already.

```yaml
installer:
- task:
    app: dotnet472
...
```
