### ISSUE TITLE
Lutris doesn't recognize p7zip as installed for Solus user

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#2069]
![](https://media.discordapp.net/attachments/538903130704838656/569231253207908362/Screenshot_from_2019-04-20_14-41-35.png)

https://packages.getsol.us/shannon/p/p7zip/

```
ERROR    2019-04-20 14:30:11,629 [errors.init:15]:This installer requires p7zip on your system
```

```
files:
- installer: https://fangamer-store.sfo2.digitaloceanspaces.com/SURVEY_PROGRAM_WINDOWS_ENGLISH.exe
game:
  arch: win32
  exe: drive_c/Program Files/SURVEY_PROGRAM/DELTARUNE.exe
  prefix: $GAMEDIR
installer:
- task:
    arch: win32
    description: Creating prefix
    name: create_prefix
    prefix: $GAMEDIR
- task:
    app: vcrun2015 win7
    arch: win32
    name: winetricks
    prefix: $GAMEDIR
- write_file:
    content: '$PLUGINSDIR

      $TEMP'
    file: $CACHE/exclude.txt
- execute:
    command: 7z x -x@"$CACHE/exclude.txt" "$CACHE/installer/SURVEY_PROGRAM_WINDOWS_ENGLISH.exe"
      -o"$GAMEDIR/drive_c/Program Files/SURVEY_PROGRAM"
- write_config:
    file: $GAMEDIR/dxvk.conf
    key: dxgi.syncInterval
    section: fps-cap
    value: 2
- write_config:
    file: $GAMEDIR/dxvk.conf
    key: dxgi.numBackBuffers
    section: fps-cap
    value: 4
require-binaries: p7zip
system:
  fps_limit: '30'
wine:
  dxvk: true
  version: tkg-4.0-x86_64
```
