### ISSUE TITLE
Dosbox script: config_file does not use set prefix

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2299]
Hello,
when you write a Dosbox Lutris script, you can specify in game section   config_file, main_file and the prefix. Lutris uses the prefix to find main_file but not for the config_file.

For example:
```
game:
  config_file: $GAMEDIR/dosbox_conf/dosbox_arena.conf
  main_file: dosbox_conf/dosbox_arena_single.conf
  prefix: $GAMEDIR
```
As you can see in this example, I had to specify the full path to the "config_file" as Lutris does not use the prefix value for it.
