### ISSUE TITLE
libretro: support bin/cue games format

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#2430]
**Describe the bug**

I want to have support for copying multiple files (bin) and selecting main file (cue or iso) automatically.

It needs new installer task, open the file picker (and allow selecting multiple files), when files are copied to destination task will automatically select iso as main file if only one file is copied, or cue file if multiple files are copied, and set main_file to the automatically selected mine file.

something like this:
```yaml
files:
- files: N/A:Please select the Dreamcast image file
game:
  core: reicast
  main_file: main_file
installer:
- copy_and_select:
    dst: $GAMEDIR
    description: "Please select the your files, iso or bin/cue"
    src: files
``` 

**Expected behavior**

Please describe the behavior you are expecting.

**Current behavior**

What is the current behavior?

**Steps to reproduce**

- 
-
-

**Lutris debugging output**

The terminal output of `lutris -d`.

Using the debug option reveals possible backtraces or missing libraries. This can help us track down your issue.

**System information**

The .json file created by typing `lutris --submit-issue` in a terminal.

**Screenshots**
