### ISSUE TITLE
`dst` argument of installer `move` commands does not get created as directory

### ISSUE THREAD

**Issue by Freso** [lutris/lutris#2715]
**Describe the bug**

If an install script has a `move: dst:` argument and `dst` does not already exist as a directory, the `src` will get installed in the location of the `dst`.

E.g.:
```yaml
- helper: https://raw.githubusercontent.com/Makaronelle/bethesda-linux-helper/master/helper.sh
[…]
- move:
    dst: $GAMEDIR/drive_c/Program Files (x86)/Bethesda.net Launcher
    src: helper
```

will install `helper.sh` as a file `Bethesda.net Launcher`. (Which in turns breaks the [Fallout 76](https://lutris.net/games/fallout-76/) installer, since `…/Bethesda.net Launcher` is not a directory.)

**Expected behavior**

Expected (and I’m pretty sure this used to be the) behaviour is that `dst` would get created as a directory and then `src` would get `move`d into it. (Current documentation says: "Move files or directories by using the move command. move requires two parameters: src (the source file or folder) and dst (the destination folder).")

**Current behavior**

`dst` directory is not created and instead `src` is created as a file in the location of `dst` (rather than as a file under the location of `dst`).

**Steps to reproduce**

- Run [Fallout 76](https://lutris.net/games/fallout-76/) installer ([lutris:fallout-76-bethesdanet-1437](lutris:fallout-76-bethesdanet-1437))
- Watch the install eventually fail (see screenshot below).

**Lutris debugging output**

https://gist.github.com/Freso/5e4b7fda559cc5d188c5f1035baf4e50/raw/43dbf4e6ebe1ce8e4b405ddaaeb7ae24ce397514/lutris.log

**System information**

https://gist.github.com/Freso/5e4b7fda559cc5d188c5f1035baf4e50/raw/43dbf4e6ebe1ce8e4b405ddaaeb7ae24ce397514/lutris-issue-report.json

**Screenshots**

![image](https://user-images.githubusercontent.com/177659/78460592-53ce8d80-76c2-11ea-87d7-a9df1ddc9baf.png)
