### ISSUE TITLE
input menu: can not add "-" symbol in options?

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2733]
Hello,
I can not put "-" symbol in an input menu code:

```
- input_menu:
    description: 'Choose your preferred game''s language:'
    id: LANG
    options:
    - riven: English
    - riven-fr: French
    - riven-de: German
    - riven-pl: Polish
    - riven-es: Spanish
    - riven-it: Italian
    - riven-jp: Japanese
    - riven-ru: Russian
    preselect: riven
```

Is it possible or is it an issue?
Thank you for your help.
