### ISSUE TITLE
feature: add "insert-disc"-like function for script without "automount", only browse to search for data

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#2809]
Hello,

could it be possible to create an "insert-disc" like function but not for disc, only for folder.
Sometimes we need to add data from a game. The folder could be recognized by a file like the "insert-disc" function, but it doesn't need automount button.
For the moment I use this function when I need data from a game to use with another game engine (exemple: Steam data from Tomb Raider I to use with GLRage - TombATI).
But the "automount" button confusing inexperiment or new users.

Like you see here:
```
- insert-disc:
    description: Please select Tomb Raider 1 Steam folder install.
    requires: GAME.GOG
- merge:
    dst: $CACHE/app
    src: $DISC
```
I used insert-disc function for a game folder, here Tomb Raider 1 Steam.
https://lutris.net/games/tomb-raider-i/

I propose two solution:
1) disable automount button:
```
- insert-disc:
    description: Please select Tomb Raider 1 Steam folder install.
    requires: GAME.GOG
    **automount: false**
- merge:
    dst: $CACHE/app
    src: $DISC
```
2) new function similar to insert-disc, but for folder:
```
- add-data-game:
    description: Please select Tomb Raider 1 Steam folder install.
    requires: GAME.GOG
- merge:
    dst: $CACHE/app
    src: $DATA
```
