### ISSUE TITLE
Steam crashes with "%appname% is no longer supported on your operating system version".

### ISSUE THREAD

**Issue by nawordar** [lutris/lutris#3077]
**Describe the bug**

When trying to install a local DiRT Rally 2.0 install script which uses winesteam runner, Steam crashes with "%appname% is no longer supported on your operating system version".

**Expected behavior**

Steam not crashing.

**Current behavior**

Steam crashes with "%appname% is no longer supported on your operating system version".

**Steps to reproduce**

1. Create the following script:
`~/lutris_scripts/dirt-rally-20.yml`:  
```yaml
name: DiRT Rally 2.0
runner: winesteam
version: DXVK
game_slug: dirt-rally-20
slug: dirt-rally-20-installer
script:
  game:
    appid: "690790"
    arch: win64
    prefix: $GAMEDIR/prefix
  winesteam:
    dxvk: true
    esync: true
    fsync: true
  installer:
    - task:
        arch: win64
        description: Creating prefix
        name: create_prefix
        prefix: $GAMEDIR/prefix
```
2. Try to install script using `lutris -i ~/lutris_scripts/dirt-rally-20.yml`

**Lutris debugging output**

```shell
❯ lutris -d -i ~/lutris_scripts/dirt-rally-20.yml
Unable to load locale dir, translations won't work.
```

**System information**

https://paste.ubuntu.com/p/PzNBSrzYZD/

**Screenshots**

![Screenshot_20200808_213312](https://user-images.githubusercontent.com/26769700/89718433-d643c280-d9be-11ea-820e-dee4a7859eb3.png)

I have tried to change emulated Windows version with:
```shell
❯ winetricks win10
```
It did not change anything, but I don't know which WINEPREFIX does the installer use, so I don't know if I have changed Windows version of the correct WINEPREFIX.
