### ISSUE TITLE
Installers can't specify Wine version

### ISSUE THREAD

**Issue by dginovker** [lutris/lutris#3213]
**Describe the bug**

When writing a game installer, the [documentation](https://github.com/lutris/lutris/blob/master/docs/installers.rst#runner-configuration-directives) says that you can put the following in:

```
wine:
        version: staging-2.21-x86_64
```

However, when running this locally, I get the following error:

`2020-10-18 17:04:03,775: Failed to retrieve wine (staging-2.21-x86_64) information`

![image](https://user-images.githubusercontent.com/32943174/96385927-19f83c80-1165-11eb-9d04-5e9d0c4e262e.png)

**Steps to reproduce**

Save the following as `errorexample.yml`

```
name: helpmechangewine
game_slug: issueslug
version: Installer
slug: installeridentifier
runner: wine

script:
    installer:
    - task:
        arch: win64
        name: create_prefix
        prefix: $GAMEDIR
    system: {}
    wine:
        version: staging-2.21-x86_64
```

Run

```
lutris -i errorexample.yml
```
