### ISSUE TITLE
Lutris beta: write_config and "false"

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#3264]
Hello Lutris dev team,
I found a problem in my Starwars Racer script: https://lutris.net/games/star-wars-episode-i-racer
My script created  a dgvoodoo2 config file during install and set logo to off:

```
- write_config:
    data:
      DirectX:
        ForceVerticalSync: true
        Resolution: max_qhd_isf
        VRAM: 256
        dgVoodooWatermark: false
      General:
        CaptureMouse: false
        FullScreenMode: false
        ScalingMode: stretched_ar
```

once the game is installed with lutris, I obained this config file:

```
[DirectX]
ForceVerticalSync=True
Resolution=max_qhd_isf
VRAM=256
dgVoodooWatermark=

[General]
CaptureMouse=
FullScreenMode=
ScalingMode=stretched_ar
```

as you can see it missed all "false" in dgvoodoo2 config file.
Why Lutris does not write "false" in the config file as requested in the installer script?
