### ISSUE TITLE
webpage Internal service error 

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#327]
I just can't save this installer

https://lutris.net/games/gog-galaxy-1112108/installer/edit/

```
files:
- game: https://cdn.gog.com/open/galaxy/client/setup_galaxy_1.1.12.108.exe
game:
  arch: win32
  exe: drive_c/Galaxy/GalaxyClient.exe
  prefix: $GAMEDIR
installer:
- task:
    description: Creating Wine prefix
    name: create_prefix
    prefix: $GAMEDIR
- task:
    key: winemenubuilder.exe
    name: set_regedit
    path: HKEY_CURRENT_USER\Software\Wine\DllOverrides
    prefix: $GAMEDIR
    type: REG_SZ
    value: ''
- task:
    app: vcrun2012
    description: Installing dlls
    name: winetricks
    prefix: $GAMEDIR
    silent: false
- task:
    app: vcrun2013
    description: Installing dlls
    name: winetricks
    prefix: $GAMEDIR
    silent: false
- task:
    app: vcrun2015
    description: Installing dlls
    name: winetricks
    prefix: $GAMEDIR
    silent: false
- task:
    app: gdiplus_winxp
    description: Installing dlls
    name: winetricks
    prefix: $GAMEDIR
    silent: false
- task:
    app: corefonts
    description: Installing dlls
    name: winetricks
    prefix: $GAMEDIR
    silent: false
- task:
    app: d3dx9
    description: Installing d3d9
    name: winetricks
    prefix: $GAMEDIR
    silent: true
- task:
    args: /DIR='C:/Galaxy' /SILENT
    description: Installing...
    executable: game
    name: wineexec
    prefix: $GAMEDIR
- task:
    key: *vcruntime140
    name: set_regedit
    path: HKEY_CURRENT_USER\Software\Wine\DllOverrides
    prefix: $GAMEDIR
    type: REG_SZ
    value: 'native,builtin'
- task:
    key: *ucrtbase
    name: set_regedit
    path: HKEY_CURRENT_USER\Software\Wine\DllOverrides
    prefix: $GAMEDIR
    type: REG_SZ
    value: 'native,builtin'
- task:
    key: *mfc140u
    name: set_regedit
    path: HKEY_CURRENT_USER\Software\Wine\DllOverrides
    prefix: $GAMEDIR
    type: REG_SZ
    value: 'native,builtin'
- task:
    app: sandbox
    description: Disabling unused WINE features
    name: winetricks
    prefix: $GAMEDIR
    silent: true
```

**Comment by sixsixfive** [comment]
apparently it is/was you website parser

**Comment by RobLoach** [comment]
You may need quotes around the `*`s....

``` yaml
files:
- game: https://cdn.gog.com/open/galaxy/client/setup_galaxy_1.1.12.108.exe
game:
  arch: win32
  exe: drive_c/Galaxy/GalaxyClient.exe
  prefix: $GAMEDIR
installer:
- task:
    description: Creating Wine prefix
    name: create_prefix
    prefix: $GAMEDIR
- task:
    key: winemenubuilder.exe
    name: set_regedit
    path: HKEY_CURRENT_USER\Software\Wine\DllOverrides
    prefix: $GAMEDIR
    type: REG_SZ
    value: ''
- task:
    app: vcrun2012
    description: Installing dlls
    name: winetricks
    prefix: $GAMEDIR
    silent: false
- task:
    app: vcrun2013
    description: Installing dlls
    name: winetricks
    prefix: $GAMEDIR
    silent: false
- task:
    app: vcrun2015
    description: Installing dlls
    name: winetricks
    prefix: $GAMEDIR
    silent: false
- task:
    app: gdiplus_winxp
    description: Installing dlls
    name: winetricks
    prefix: $GAMEDIR
    silent: false
- task:
    app: corefonts
    description: Installing dlls
    name: winetricks
    prefix: $GAMEDIR
    silent: false
- task:
    app: d3dx9
    description: Installing d3d9
    name: winetricks
    prefix: $GAMEDIR
    silent: true
- task:
    args: /DIR='C:/Galaxy' /SILENT
    description: Installing...
    executable: game
    name: wineexec
    prefix: $GAMEDIR
- task:
    key: "*vcruntime140"
    name: set_regedit
    path: HKEY_CURRENT_USER\Software\Wine\DllOverrides
    prefix: $GAMEDIR
    type: REG_SZ
    value: 'native,builtin'
- task:
    key: "*ucrtbase"
    name: set_regedit
    path: HKEY_CURRENT_USER\Software\Wine\DllOverrides
    prefix: $GAMEDIR
    type: REG_SZ
    value: 'native,builtin'
- task:
    key: "*mfc140u"
    name: set_regedit
    path: HKEY_CURRENT_USER\Software\Wine\DllOverrides
    prefix: $GAMEDIR
    type: REG_SZ
    value: 'native,builtin'
- task:
    app: sandbox
    description: Disabling unused WINE features
    name: winetricks
    prefix: $GAMEDIR
    silent: true
```
