### ISSUE TITLE
blank installation script dialog box

### ISSUE THREAD

**Issue by silverhikari** [lutris/lutris#3290]
**Describe the bug**

when using a yml script such as the mod manger 2 script i get a dialog box with only the cache button and nothing else.

**Steps to reproduce**
1. download yml script from https://github.com/rockerbacon/lutris-skyrimse-installers
2. in terminal do 'lutris -i /pathtoscript/modorganizer2.yml
3. tab popsup empty
**Lutris debugging output (Optional)**

INFO     2020-11-16 15:28:56,053 [application.do_command_line:319]:Lutris 0.5.8
INFO     2020-11-16 15:28:56,055 [startup.check_driver:61]:Using NVIDIA drivers 455.38 for x86_64
INFO     2020-11-16 15:28:56,055 [startup.check_driver:65]:GPU: GeForce GTX 670
INFO     2020-11-16 15:28:56,055 [startup.check_driver:81]:GPU: 10DE:1189 3842:2678 (nvidia drivers)
DEBUG    2020-11-16 15:28:56,645 [__init__.read_script:37]:Loading script(s) from /home/silver/Downloads/modorganizer2.yml
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 456, in do_command_line
    self.show_installer_window(installers)
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 252, in show_installer_window
    self.show_window(
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 246, in show_window
    window_inst = window_class(application=self, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 97, in __init__
    self.choose_installer()
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 123, in choose_installer
    self.validate_scripts()
  File "/usr/lib/python3/dist-packages/lutris/gui/installerwindow.py", line 115, in validate_scripts
    script[item] = script.get(item) or ""
AttributeError: 'str' object has no attribute 'get'
DEBUG    2020-11-16 15:28:56,767 [http.get:73]:GET https://lutris.net/api/runtimes
DEBUG    2020-11-16 15:28:56,984 [http.get:73]:GET https://lutris.net/api/runtimes/icons

**System information (Optional)**
https://pastebin.com/nDRYppWp
**Screenshots (Optional)**

![Screenshot_20201116_152958](https://user-images.githubusercontent.com/25397212/99305120-5761ef80-2821-11eb-8bb5-cf845a9ae0bc.png)

**Comment by leycec** [comment]
**Yikes.** @AshenPaladin just reported the exact same issue with our own previously working Lutris installers at leycec/aokana-linux#2. Sadly, this appears to be a regression in Lutris 0.5.8 (released five days ago) of #3227 – a similar issue thought to be resolved a month ago. `</sigh>`

@strycore: Since this regressed, would it be feasible to add a new functional test to the Lutris test suite exercising installation of external scripts from the command line via `lutris -i`? It'd be sweet if we could definitively nail this down! :hammer:

**Comment by dhollinger** [comment]
I wasn't sure if this was a bug or not. I can get an installer to work if the entire thing is wrapped with a top level key of `results`:

Example of my local installer for  Torchlight:
```yaml
results:
  - game_slug: torchlight
    name: Torchlight
    runner: linux
    slug: torchlight-humble
    version: Humble
    humbleid: torchlight
    humblestoreid: torchlight
    humblestoreid_real: torchlight
    script:
      files:
      - game: 'N/A: Please select the .sh install file downloaded from humblebundle.com'
      - sdl: 'https://github.com/dhollinger/lutris_installers/releases/download/v1.0.0/libSDL2-2.0.so.0.tar.gz'
      game:
        exe: $GAMEDIR/Torchlight/Torchlight.bin.x86_64
      installer:
      - execute:
          args: -u -r -l -d $GAMEDIR -b $GAMEDIR --nox11 --packager dpkg --ignore-failed-deps
          file: game
      - extract:
          file: sdl
          dst: $GAMEDIR/Torchlight/lib64
```
