### ISSUE TITLE
File download mirrors

### ISSUE THREAD

**Issue by FakeShemp** [lutris/lutris#3309]
Would it be possible to add the functionality that a downloadable file can also have alternative mirrors?

For example, I have this 

```yaml
files:
- file: http://url.net/game.zip
```

and maybe it could be possible to also do

```yaml
files:
- file: http://url.net/files/game.zip
  mirrors: [ http://url2.net/game.zip, http://url3.net/game.zip, http://url4.net/game.zip ]
```

so that if one server fails to connect, another one could be tried instead.
