### ISSUE TITLE
Lutris Wine prefix set to None? (Fallout: New Vegas)

### ISSUE THREAD

**Issue by olof-nord** [lutris/lutris#3449]
Hello community!

During the installation of Fallout: New Vegas (a game I already have installed, but cannot start through Steam) through Lutris, something went wrong.

Install procedure:

https://lutris.net/games/fallout-new-vegas/
Select "Steam (Windows) Steam version"
Happily follow all the automated steps done which I have failed to manually do in the past
Install complete.
Start game: nothing happens.

Here is my log:

```
lutris-wrapper: Fallout: New Vegas
Running /home/olof/.local/share/lutris/runners/wine/lutris-6.0-x86_64/bin/wine None/launch.exe
Initial process has started with pid 179375
Start monitoring process.
wineserver: using server-side synchronization.
wine: cannot find L"None/launch.exe"
Monitored process exited.
Initial process has exited (return code: 13568)
All monitored processes have exited.
Exit with returncode 13568
```
The game is installed to $HOME/None. That might not be the intended destination however looking into it, there is a `launch.exe` file available.

```
➜  ~ ls -la $HOME/None
total 7376
drwxr-xr-x  4 olof olof    4096 Feb 27 22:12 .
drwxr-xr-x 76 olof olof    4096 Feb 27 22:35 ..
-rwxr-xr-x  1 olof olof 4836864 Jun 21  2018 boss.exe
lrwxrwxrwx  1 olof olof      57 Feb 27 22:12 config -> 'prefix/drive_c/users/olof/My Documents/My Games/FalloutNV'
drwx------  6 olof olof    4096 Jun 22  2018 Data
-rw-r--r--  1 olof olof     604 Feb 27 22:12 Fallout_default.ini
-rw-r--r--  1 olof olof      38 Feb 27 22:12 FalloutNVpatch.bat
-rw-r--r--  1 olof olof   46080 Jun 21  2018 FalloutNVpatch.exe
-rw-r--r--  1 olof olof     795 Feb 27 22:12 install.bat
-rw-rw-r--  1 olof olof      65 Jun 21  2018 launch.bat
-rw-r--r--  1 olof olof   19672 Jun 22  2018 launch.exe
-rw-rw-r--  1 olof olof    1056 Jun 21  2018 launch_menu.bat
-rw-r--r--  1 olof olof  955392 Oct 11  2017 nvse_1_4.dll
-rw-r--r--  1 olof olof  955392 Oct 11  2017 nvse_1_4ng.dll
-rw-r--r--  1 olof olof  366080 Oct 11  2017 nvse_editor_1_4.dll
-rw-r--r--  1 olof olof  123904 Oct 11  2017 nvse_loader.exe
-rw-r--r--  1 olof olof    5802 Jan 22  2017 nvse_readme.txt
-rw-r--r--  1 olof olof  123904 Oct 11  2017 nvse_steam_loader.dll
-rw-r--r--  1 olof olof   58001 Oct 11  2017 nvse_whatsnew.txt
drwxr-xr-x  3 olof olof    4096 Feb 27 22:13 prefix
```

Anything I am missing here?

Lutris 0.5.8.3

➜  ~ /home/olof/.local/share/lutris/runners/wine/lutris-6.0-x86_64/bin/wine --version
wine-6.0.r0.g2414b1da ( TkG Staging Esync Fsync )

Arch Linux, 5.11.1-arch1-1, x86_64

Happy to provide further logs or info.

**Comment by piatikantrop** [comment]
I have the same problem trying to install Far Cry 4 from lutris.

**Comment by pakro** [comment]
It seems that `$GAMEDIR` is not set.
If you look at https://lutris.net/games/install/9599/view (see small snippet below)
```
files:
- wallpaper: https://gist.github.com/daniel-j/28c6d207c5393aa64c3a9d8ee26d1425/raw/wallpaper-falloutnv.tar.xz
- launchmenu: https://gist.github.com/daniel-j/953311dec023c4c1b77103a085e1151a/archive/master.tar.gz
- modpack: https://djazz.se/nas/games/falloutnv/modpack.tar.xz
game:
  appid: 22380
  arch: win64
  exe: $GAMEDIR/launch.bat
  prefix: $GAMEDIR/prefix
  run_without_steam: true
  steamless_binary: $GAMEDIR/launch.exe
```
Then you see that None comes probably because $GAMEDIR is not set. Unfortunately I'm not sure who is responsible to set `$GAMEDIR`. But maybe someone else can answer that question.

BTW I have the same issue and I'm using the lutris-git.
