### ISSUE TITLE
Winetricks dotnet installation hangs

### ISSUE THREAD

**Issue by AsciiWolf** [lutris/lutris#3480]
I am not sure where to report this as it seems to be working fine with regular Wine outside of Lutris. I am working on an installer for Lineage 2 that requires .NET to be installed. Unfortunately, both dotnet462 and dotnet472 (and some other dotnet versions that I tried) seem to hang forever for hours without any progress. And as I said, it seems to happen only when using Lutris (with lutris-6.0-x86_64 Wine).

Here is the Lutris script I work on:
```
files:
- ncsoftlauncher: https://launcher.patcher.ncsoft.com/NCLauncher2_Installer.exe
game:
  arch: win64
  exe: drive_c/Program Files (x86)/NCSOFT/NC Launcher 2/NCLauncher2.exe
  prefix: $GAMEDIR
installer:
- task:
    arch: win64
    name: create_prefix
    prefix: $GAMEDIR
- task:
    app: dotnet472
    arch: win64
    description: Installing .NET 4.7.2
    name: winetricks
    prefix: $GAMEDIR
- task:
    arch: win64
    executable: ncsoftlauncher
    name: wineexec
    prefix: $GAMEDIR
wine:
  UseGLSL: disabled
  dxvk: true
  esync: true
```

**Comment by briaguya-ai** [comment]
i was able to reproduce your issue, tons of fixme errors all over the place during the 472 install, so i tried 4.8, which got me here

```
files:
- ncsoftlauncher: https://launcher.patcher.ncsoft.com/NCLauncher2_Installer.exe
game:
  arch: win64
  exe: drive_c/Program Files (x86)/NCSOFT/NC Launcher 2/NCLauncher2.exe
  prefix: $GAMEDIR
installer:
- task:
    arch: win64
    name: create_prefix
    prefix: $GAMEDIR
- task:
    arch: win64
    executable: ncsoftlauncher
    name: wineexec
    prefix: $GAMEDIR
- task:
    app: dotnet48
    arch: win64
    description: Installing .NET 4.8
    name: winetricks
    prefix: $GAMEDIR
wine:
  UseGLSL: disabled
  dxvk: true
  esync: true
```

with this i was able to get through the install. the launcher crashes for me on startup after that
