### ISSUE TITLE
Feature Request: Allow Dynamic -file: parameters in install scripts

### ISSUE THREAD

**Issue by gardotd426** [lutris/lutris#3918]
So, there are instances, *especially* standalone mods like from moddb, where the game/installer file link is not permanent, but is always changing. For example, I recently wrote the new installer for the Anomaly standalone S.T.A.L.K.E.R. mod and it eventually got published. However, the link is dead because of the way they use their mirrors.

Here's how it works:

For each game, there's a base url. For Anomaly, it's https://www.moddb.com/downloads/mirror/207799/121 with 121 being the mirror number (there's any one of several mirrors, you can use any of them. But that alone gets you nowhere. The full link as of me typing this to download the file is  https://www.moddb.com/downloads/mirror/207799/114/458d9b0d207635c9d3f2be487355d61d/?referer=https%3A%2F%2Fwww.moddb.com%2F

That hash, `458d9b0d207635c9d3f2be487355d61d`, is what changes, and it changes every couple hours. So the original installer doesn't work unless the user downloads the Anomaly-1.5.1.2.7z file themselves and provides it during the installation. Sure, that's not a huge deal, but not ideal at all.

I actually contacted the devs over at moddb and explained the issue, and they provided me with a way to always get the current hash and correct download link. And I have a little bash script that will always grab the correct url and hash, turn it into a url that wget can parse, and download the file to `Anomaly-1.5.1.2.7z`.

```
#!/bin/bash
url="$(wget -q -O -  https:// www.moddb.com/downloads/start/207799 | grep /downloads/mirror/207799 | cut -d= -f2 | cut -d">" -f1 | cut -d";" -f1 | grep https | jq -r)"

wget -q $url -O Anomaly-1.5.1.2.7z
```

So, I edited the current install script (I haven't submitted the edits yet but I will shortly) and have tested it several times. 

Right now, it looks like this:

```
files:
- script: https://raw.githubusercontent.com/gardotd426/Anomalyscript/main/urlvar.sh
game:
  exe: drive_c/anomaly/AnomalyLauncher.exe
  prefix: $GAMEDIR
  working_dir: $GAMEDIR/drive_c/anomaly
installer:
- task:
    arch: win64
    description: Creating Wine prefix
    name: create_prefix
    prefix: $GAMEDIR
- execute:
    command: mkdir "$GAMEDIR/drive_c/anomaly"
- chmodx: script
- execute:
    file: script
- extract:
    arch: win64
    dst: $GAMEDIR/drive_c/anomaly
    file: $GAMEDIR/Anomaly-1.5.1.2.7z
    format: 7z
wine:
  dxvk: true
  esync: true
  version: lutris-fshack-6.14-4-x86_64
```

So what it's doing is just pulling in my script that I wrote with the help of the moddb guys that will download the `Anomaly-1.5.1.2.7z` file no matter what the current hash is, and then using that to download the archive and extracting it to the correct location. 

It works perfectly, 100% of the time. It will always work (until Anomaly is updated which will be months from now, that's a different issue, same as any other versioned file). But the problem is I can't provide it in the files section. 

So the script will always work, you just click install, let it do it's thing, then click launch and it works OOTB with zero issues, but I feel like I should be able to provide a sort of bash script or environment variable for the file instead. Something like:

```
files:
- script: https://raw.githubusercontent.com/gardotd426/Anomalyscript/main/urlvar.sh
- archive:
    url: $(wget -q -O -  https:// www.moddb.com/downloads/start/207799 | grep /downloads/mirror/207799 | cut -d= -f2 | cut -d">" -f1 | cut -d";" -f1 | grep https | jq -r)
    filename: Anomaly-1.5.1.2.7z
```
If it were able to parse that command, then the url would always be correct. I've written about 1 python patch in my life so I have no idea how this could be implemented or I'd file the PR itself, or if it's even something you guys would be willing to do. But I think it would be cool. 

As it stands though, the script I posted above does work, and will work regardless of when the current mirror link hash changes. So I'll submit the updated installer. 

I know this sounds  kind of confusing, so if any clarification is needed I'm happy to answer any questions.

For reference, here's the original that no longer works because of the expired link:

```
files:
- client: https://www.moddb.com/downloads/mirror/207799/123/fc30ca003ca55b47b54be96c75f24120/?referer=https%3A%2F%2Fwww.moddb.com%2Fmods%2Fstalker-anomaly%2Fdownloads%2Fstalker-anomaly-151
game:
  exe: drive_c/anomaly/AnomalyLauncher.exe
  prefix: $GAMEDIR
  working_dir: $GAMEDIR/drive_c/anomaly
installer:
- task:
    arch: win64
    description: Creating Wine prefix
    name: create_prefix
    prefix: $GAMEDIR
- execute:
    command: mkdir "$GAMEDIR/drive_c/anomaly"
- extract:
    arch: win64
    dst: $GAMEDIR/drive_c/anomaly
    file: client
    format: 7z
wine:
  dxvk: true
  esync: true
  version: lutris-fshack-6.14-4-x86_64
```
