### ISSUE TITLE
Better handling of default Wine version

### ISSUE THREAD

**Issue by rkben** [lutris/lutris#4337]
Setting the Wine Version under the Wine runner is not respected when installing an executable.

Eg. `runners/wine.yml`
```yml
system:
  disable_compositor: false
wine:
  battleye: false
  eac: false
  esync: false
  fsr: false
  fsync: false
  version: lutris-GE-Proton7-15-x86_64
```

Will set any new prefix with Lutris' default (`lutris-fshack`) wine version instead of `lutris-GE-ProtonX-xx`.

- Lutris Version: 0.5.10.1
