### ISSUE TITLE
The requires command is broken because Lutris does not allow two installation windows to be open at the same time

### ISSUE THREAD

**Issue by SwimmingTiger** [lutris/lutris#4539]
In 0.5.7 or earlier, Lutris allowed multiple installation windows to be open at the same time, so the following installation script works fine:

https://lutris.net/games/install/9849/view

```
files:
- lovefile: https://github.com/AlexanDDOS/Phibonacci/releases/download/v0.1/phibonacci.love
game:
  args: $GAMEDIR/phibonacci.love
  exe: love
installer:
- move:
    dst: $GAMEDIR/phibonacci.love
    src: $lovefile
requires: love2d
```

Now at the 0.5.11, if you don't install [love2d](https://lutris.net/games/love2d/) before installing [2048](https://lutris.net/games/2048/), it will no longer work because the install window for love2d will disappear as soon as it appears.

So, the requires command is actually broken at 0.5.11.

A GIF for this:

![录屏_选择区域_20221003202513](https://user-images.githubusercontent.com/4986069/193576308-20eab3be-1a16-4250-bfe1-80a6b179e95b.gif)
