### ISSUE TITLE
Diablo 4 - stuck at loading screen

### ISSUE THREAD

**Issue by jisage** [lutris/lutris#4567]
By using `lutris-fshack-7.2-x86_64`, it's possible to overcome the ["No GPUs found" issue](4566).

But the game is stuck at the loading screen - D4 logo with mouse spinning forever.

**Comment by lorschy** [comment]
Is there a solution in sight yet ?

**Comment by jisage** [comment]
> Is there a solution in sight yet ?

I don't think so... Also I'm not sure which "state" is better, the infinite loading, or the "No GPUs found".

At some point I made it work with the following settings:

```
game:
  arch: win64
  exe: drive_c/Program Files (x86)/Battle.net/Battle.net.exe
  prefix: /home/jisage/Games/battlenet
system:
  disable_compositor: false
  disable_runtime: false
  env:
    DXVK_CONFIG_FILE: /home/jisage/Games/battlenet/dxvk.conf
    DXVK_STATE_CACHE_PATH: /home/jisage/Games/battlenet
    STAGING_SHARED_MEMORY: '1'
    __GLX_VENDOR_LIBRARY_NAME: nvidia
    __GL_DXVK_OPTIMIZATIONS: '1'
    __GL_SHADER_DISK_CACHE: '1'
    __GL_SHADER_DISK_CACHE_PATH: /home/jisage/Games/battlenet
    __NV_PRIME_RENDER_OFFLOAD: '1'
    __VK_LAYER_NV_optimus: NVIDIA_only
  exclude_processes: Agent.exe "Battle.net Helper.exe"
  gamemode: false
  manual_command: /home/jisage/Games/battlenet/state-cache-merge/state-cache-update.sh
  prefer_system_libs: false
  pulse_latency: true
wine:
  battleye: false
  custom_wine_path: ''
  d3d_extras: true
  dxvk: true
  dxvk_nvapi: false
  eac: false
  esync: false
  fsr: false
  fsync: false
  show_debug: ''
  system_winetricks: false
  version: winehq-staging
  vkd3d: true
```

**Important note**:

It works ONLY with hybrid mode on the graphics. So if the system has 2 GPUs (like most laptops these days), it must be in the mode where both GPUs are active. And enable piping through the NVidia card, with these `env` variables that you see above.

It does NOT work if the NVidia card is forced to be used by default.

These 2 modes can be swapped (for example) with [envycontrol](https://github.com/bayasdev/envycontrol):

```
sudo envycontrol --switch hybrid
sudo systemctl reboot
```

---

I'm sure this can eventually be fixed by more knowledgeable people around drivers and wine. But I guess the game has to be released first, in order to get more people on this.
