### ISSUE TITLE
How to open/create game launch menu in Lutris?

### ISSUE THREAD

**Issue by junglized** [lutris/lutris#4661]
Hi all,

This is rather a cry for help rather than issue report. I have installed Dungeon SIege with it's DLC. Executables for both, main game and expansion, are in the same folder. To launch main game or DLC I need to change path to executable file in game settings in Lutris.

But I noticed that launching Carmageddon: Max Damage a little popup menu shows up allowing me to select which version of the game I want to play, without installing any additional software. Because the little menu is displayed as Linux native window I thought this might be Lutris feature I don't know how to enable/run.

Is there a way to do the same with Dungeon Siege (or any other game)?

Thank you.

--------
Here's the screenshot of said menu for Carmageddon.

![image](https://user-images.githubusercontent.com/26525585/208241245-d60c794d-7a55-4e5a-bf82-7a6838dc7bae.png)

**Comment by junglized** [comment]
So I've successfully created a launcher using .yml file residing in ~/.config/lutris/games (at least in Linux Mint), with a little hint from @danieljohnson2 in this thread #4648. 

This is how it looks like after modification. The part creating additional launch options is in `launch_configs` right under `exe` entry. There is no need to create additional launch config for the main game as this is default option and shows up in launcher anyways. There is also space for launch attributes in `args` (I don't have any in this example though).

```
game:
  arch: win32
  exe: /home/junglized/Games/Dungeon Siege/drive_c/Program Files/Microsoft Games/Dungeon
    Siege/dungeonsiege.exe
  launch_configs:
  - args:
    exe: DSLOA.exe
    name: Legends of Aranna
  prefix: ~/Games/Dungeon Siege
system: {}
wine:
  overrides:
    D3D8: n,b
    D3Dimm: n,b
    DDraw: n,b
  version: lutris-7.2-2-x86_64
```
