### ISSUE TITLE
Add github releases as a source for installer files

### ISSUE THREAD

**Issue by CrimsonFork** [lutris/lutris#4826]
Example: I've a script that downloads the needed file through a bash command, so the logical thing to do would be
```yaml
game:
  exe: $GAMEDIR/exe
installer:
- execute:
    command: 'bash'
```
However this fails as that way `$GAMEDIR` is `None`. A workaround right now would be to download a file for the sake of it, but I somehow doubt that is intended behavior.
```yaml
files:
- dummy-file:
    filename: 'Lutris GAMEDIR fix (can be any file)'
    url: https://codeberg.org/cf/lutris/raw/branch/main/gamedir-fix
    game:
  exe: $GAMEDIR/exe
installer:
- move:
    dst: dummy-file
    src: dummy-file
- execute:
    command: 'bash'
```

**Comment by danieljohnson2** [comment]
If you are downloading a file anyway, why not use 'files' to do it?

**Comment by strycore** [comment]
I believe this was fixed in 0.5.13 or I fixed a very similar issue.

**Comment by strycore** [comment]
Also, if a file requires special things to download, please create an issue so any solution using wget or curl is temporary

**Comment by strycore** [comment]
Since this use case is fairly frequent we could have something like:

```
files:
- prism-launcher:
    type: github
    repo: PrismLauncher/PrismLauncher
    release: latest
    format: AppImage
```

**Comment by CrimsonFork** [comment]
I feel like it'd be better to have a generic git module and provide a URL to the repo. Also there can be more than one file of the same format per release, so maybe pattern matching is more appropriate?

```yaml
files:
- prism-launcher:
    type: git
    repo: github.com/PrismLauncher/PrismLauncher
    release: latest
    name: .*\.AppImage
```
