### ISSUE TITLE
name and game-slug are missing from yaml config for locally installed games

### ISSUE THREAD

**Issue by nioncode** [lutris/lutris#5004]
### Bug description

When you add a locally installed game, its yml config in `~/.var/app/net.lutris.Lutris/config/lutris/games` does not contain the `name` and `game-slug` fields.

These are required by external tools to look up the game, e.g. to backup its save games (see https://github.com/mtkennerly/ludusavi/issues/209). It would be great if the installer (or edit dialog, whenever you modify an already installed game) would store the name and game-slug in the config (currently it seems to just be stored in `pga.db`). Is there a reason for having both, the yml config and `pga.db` with potentially overlapping data that must be kept in sync?

### How to Reproduce

1. Add a locally installed game
2. Check its config via `cat ~/.var/app/net.lutris.Lutris/config/lutris/games/mygame-123456.yml`
3. See only:
```
game:
  exe: /home/deck/Games/mygame/mygame.exe
  prefix: /home/deck/lutrix-prefixes/mygame
system: {}
wine:
  version: lutris-GE-Proton8-14-x86_64
```

### Expected behavior

The config should contain the name and game-slug, like:
```
game:
  exe: /home/deck/Games/mygame/mygame.exe
  prefix: /home/deck/lutrix-prefixes/mygame
name: My Game
game-slug: my-game
system: {}
wine:
  version: lutris-GE-Proton8-14-x86_64
```

### Log output

```shell
irrelevant
```

### System Information

```shell
irrelevant
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.
