### ISSUE TITLE
Use of `launch_configs` Does Not Work for Games with `requires` Statement

### ISSUE THREAD

**Issue by manuth** [lutris/lutris#5258]
I was trying to create a custom installer for a game from Epic Games Store.
However, when launching the game, the dialogue for choosing the launch config does not show up.

Here is a (not so) minimal example of this happening:

<details>
<summary>Installer Source</summary>

```yml
files:
- shim:
    filename: shim.zip
    url: https://github.com/kiennq/scoop-better-shimexe/releases/download/v3.0/shimexe.zip
game:
  args: ''
  exe: $GAMEDIR/drive_c/Program Files/Epic Games/KH_1.5_2.5/launch.vbs
  launch_configs:
  - args: KINGDOM HEARTS FINAL MIX.exe
    exe: $GAMEDIR/drive_c/Program Files/Epic Games/KH_1.5_2.5/launch.vbs
    name: Kingdom Hearts Final Mix
installer:
- task:
    args: -opengl -SkipBuildPatchPrereq -com.epicgames.launcher://apps/68c214c58f694ae88c2dab6f209b43e4?action=install
    description: The Epic Game Store will now open. Please launch the installation
      of KINGDOM HEARTS HD 1.5+2.5 ReMIX then close the EGS client once the game has
      been downloaded.
    executable: $GAMEDIR/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe
    name: wineexec
    prefix: $GAMEDIR
- task:
    app: wsh57 vcrun6
    description: Installing Windows Scripting requirements...
    name: winetricks
    silent: true
- move:
    dst: $GAMEDIR/drive_c/Program Files/Epic Games/KH_1.5_2.5/KINGDOM HEARTS HD 1.5+2.5
      ReMIX.bak.exe
    src: $GAMEDIR/drive_c/Program Files/Epic Games/KH_1.5_2.5/KINGDOM HEARTS HD 1.5+2.5
      ReMIX.exe
- extract:
    dst: $CACHE/shim
    file: shim
- copy:
    dst: $GAMEDIR/drive_c/Program Files/Epic Games/KH_1.5_2.5
    src: $CACHE/shim/shim.exe
- move:
    dst: $GAMEDIR/drive_c/Program Files/Epic Games/KH_1.5_2.5/KINGDOM HEARTS HD 1.5+2.5
      ReMIX.exe
    src: $GAMEDIR/drive_c/Program Files/Epic Games/KH_1.5_2.5/shim.exe
- write_file:
    content: 'Set fso = CreateObject("Scripting.FileSystemObject")

      scriptDir = fso.GetParentFolderName(WScript.ScriptFullName)

      appFileName = fso.BuildPath(scriptDir, "app.txt")


      If fso.FileExists(appFileName) Then

      fso.DeleteFile(appFileName)

      End If


      If WScript.Arguments.Count > 0 Then

      Set appFile = fso.CreateTextFile(appFileName)

      appFile.Write(WScript.Arguments(0))

      appFile.Close

      End If


      WScript.CreateObject("WScript.Shell").Run("""C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32\EpicGamesLauncher.exe""
      -opengl -SkipBuildPatchPrereq -com.epicgames.launcher://apps/68c214c58f694ae88c2dab6f209b43e4?action=launch")'
    file: $GAMEDIR/drive_c/Program Files/Epic Games/KH_1.5_2.5/launch.vbs
- write_file:
    content: 'Dim args, gameFile, scriptDir, entryPoint

      Set fso = CreateObject("Scripting.FileSystemObject")

      args = ""

      gameFile = ""

      scriptDir = fso.GetParentFolderName(WScript.ScriptFullName)

      appFileName = fso.BuildPath(scriptDir, "app.txt")

      If fso.FileExists(appFileName) Then

      Set appFile = fso.OpenTextFile(appFileName, 1)

      gameFile = Trim(appFile.ReadAll())

      appFile.Close

      fso.DeleteFile(appFileName)

      Else

      gameFile = "KINGDOM HEARTS HD 1.5+2.5 ReMIX.bak.exe"

      End If

      For i=0 To WScript.Arguments.Count - 1

      args = args & " " & WScript.Arguments(i)

      Next

      entryPoint = fso.BuildPath(scriptDir, gameFile)

      WScript.CreateObject("WScript.Shell").Run("""" & entryPoint & """" & args)'
    file: $GAMEDIR/drive_c/Program Files/Epic Games/KH_1.5_2.5/run.vbs
- write_file:
    content: 'path = wscript.exe

      args = "C:\Program Files\Epic Games\KH_1.5_2.5\run.vbs"'
    file: $GAMEDIR/drive_c/Program Files/Epic Games/KH_1.5_2.5/KINGDOM HEARTS HD 1.5+2.5
      ReMIX.shim
requires: epic-games-store
```

</details>

#### Expected Behavior

The dialog for choosing between the main config and "Kingdom Hearts Final Mix" should appear.

#### Actual Behavior

The main `exe` is launched.
