### ISSUE TITLE
Bug: "write_json"-function corrupts json files when modifying them

### ISSUE THREAD

**Issue by praxostech** [lutris/lutris#5292]
* Used Lutris version: 0.5.16 (Flatpak)
* Used distro: Linux Mint 21.3 Cinnamon

The "write_json"-function (used in Lutris installer scripts) corrupts JSON files, if you use it to modify values in a JSON file.
If you set a new value for a key and the new value is shorter than the old value, the resulting JSON file is appended parts of the original value and a closing curly bracket.
This is not always the case, the string length of the new value has to be smaller than a certain length.

I could not find out how short the string for the new value has to be in general, but from my test results I can tell, that:
* Replacing an old value (string length = 20) with a new value (string length >= 15) works without problems.
* Replacing it with a new value (string length < 15) will create a corrupted JSON file.

## How to reproduce the bug

1. Create a JSON file with the following contents and name it "test.json":
```
{"hello":"AAAAABBBBBAAAAABBBBB"}
```

2. Create a Lutris install script (YAML file) with the following contents:
```
name: My Game
game_slug: my-game
version: Installer
slug: my-game-installer
runner: linux
script:
  game:
    exe: /usr/bin/true
    working_dir: $GAMEDIR
  files:
  - myfile: "N/A: Select the JSON file"

  installer:
    - merge:
        src: myfile
        dst: $GAMEDIR
    - write_json:
        file: $GAMEDIR/test.json
        data:
            "hello": "CCCCCCCCCC"
```

3. Run the installer script and select the JSON file created in step one when asked

The expected file content of *test.json* in the $GAMEDIR would be:
```
{
  "hello": "CCCCCCCCCC"
}
```

The actual content is:
```
{
  "hello": "CCCCCCCCCC"
}BBB"}
```
