### ISSUE TITLE
Game files do not get deleted when removing a game from the library

### ISSUE THREAD

**Issue by praxostech** [lutris/lutris#5297]
## Problem description
If you remove a game from your library via the GUI and you have ticked the checkbox "Delete files",
Lutris will only remove the game from the library, but does not delete the game files/the game´s directory.

## System information
* Distro: Linux Mint 21.3 Edge (fresh installation)
* Lutris version: 0.5.16 (Flatpak from Flathub) (fresh installation)
* OS: GNOME 45 Flatpak runtime
* Arch: x86_64
* Kernel: 6.5.0-15-generic
* Desktop: X-Cinnamon
* Display Server: x11

## Steps to reproduce
1. Add a game with at least one file in it`s directory.
You can run this small script to do so, I used it for my test.

```
name: My Game
game_slug: my-game
version: Installer
slug: my-game-installer
runner: linux
script:
  game:
    exe: /usr/bin/true
    working_dir: $GAMEDIR
  files:
  - myfile: "N/A: Select a test file"

  installer:
    - merge:
        src: myfile
        dst: $GAMEDIR
```

2. From the Lutris GUI, right click on the game and select the option "Remove".
3. In the "Remove Games" window, tick the checkboxes "Delete Files" and "Remove From Library" and hit the button "Uninstall"

## Lutris terminal output (from steps 2 & 3)
```
Removing Steam shortcut for My Game (linux)
Failed to trash folder /home/USERNAME/Games/my-game: The folder could not be moved to the trash.
NoneType: None
```

If you have any questions, feel free to ask :)
