### ISSUE TITLE
Command line silent install / install without confirmation window poping up

### ISSUE THREAD

**Issue by NBOOK** [lutris/lutris#5450]
Hi, I'm trying to automate my game installation using yaml configurations and command line.
Command: `net.lutris.Lutris --install ~/test.yaml`
configuration (test.yaml):
```
name: My Test Game
game_slug: test-game
slug: installer-test-game
version: test-game-v1
runner: wine
script:
  game:
    exe: "/home/user/game/start.exe"
    prefix: /home/user/env
  system:
    locale: en_US.utf8
  wine:
    version: wine-ge-8-26-x86_64
```
After excuting the command a confirmation window will pop up, I wonder if there's way to bypass the confirmation window, like using a `-y` argument in the command line?
![Screenshot_20240425](https://github.com/lutris/lutris/assets/16967347/5c0b9828-c430-4bfe-826b-8c1803931965)

There are some other related issues #2907 and #3029, but they are 4y ago and the arguments there cannot be recognized in the current version. Any ideas are appreciated, thanks.
