### ISSUE TITLE
Allow to bundle multiple executables

### ISSUE THREAD

**Issue by basxto** [lutris/lutris#607]
Like GLX, SDL and server for Xonotic
or map editor and game for MegaGlest
or to directly launch into the map editor of Wesnoth.

It would make sense to hide the alternate versions in the context menu.

**Comment by strycore** [comment]
Yep, that's something I've wanted as well for a while… Approved!

**Comment by Ryochan7** [comment]
I wanted to make an installer script for the GOG release of Civilization 4 Complete only to find out that the single executable limit makes that impossible. The Civ 4 version of Colonization is bundled as a separate executable so switching between normal Civ 4 and Colonization requires extra work to be done to have access to both games. Unfortunately, Colonization is very crashy on Wine so it didn't really matter anyway. Performance was really good otherwise. It was a fun way to celebrate Columbus Day tbh.

**Comment by basxto** [comment]
Now that I think abot it, you could write a script, which asks the the user via zenity.
Starting one version by default if zenity is not found.
But that’s a bit hacky.

**Comment by hollunder** [comment]
Definitely a sorely missing feature. PoL can do it. Well, it doesn't group them unless you name them accordingly, but at least you can have multiple executables.
I stumbled upon this issue just now with Dawn of War, which has three +  graphics configurator. External graphics configurator programs and similar are quite common and right now you have to 'run a exe' and hunt down the file each time.

**Comment by sigboe** [comment]
![untitled](https://user-images.githubusercontent.com/2087930/63679140-e89a1000-c7f0-11e9-9e7d-59b6990335a4.png)

Some examples where the button could be. 
Also maybe it could be launched via a shortcut like `lutris lutris:rungameid/83a` where the `a` letter following the id number would designate the first extra shortcut.

**Usecase 1:**
Add battle.net games like Diablo 3 and make them launch directly without Battle.net, and have a shortcut to open battle.net in the prefix to update and what not.

**Usecase 2:**
Add configuration utilities, some games have configurations in a seperate App

**Usecase 3:**
Open Map Editor or similar additional program

**Usecase 4:**
Open a modded version of the EXE, like skyrim script extender.

**Usecase 5:**
Open a trainer

**Comment by DenpaBorisu** [comment]
for battle net games just add "-launch" as a launching command to avoid the battle.net launcher
![Screenshot_30_230903](https://user-images.githubusercontent.com/22583225/65929170-5a104400-e3d7-11e9-8936-754ae95244fc.png)

**Comment by basxto** [comment]
> and have a shortcut to open battle.net in the prefix to update and what not.

**Comment by ColonelPhantom** [comment]
Personally, I think where the alternate option would be best really depends on what the alternate version does. For example, with Xonotic it makes sense to put one as default and hide the other (and make that an option or something). With battle.net or other launchers, it would make more sense to do something like put it next to the Configure button. And when there are simply multiple variants of the game where there shouldn't really be one default, like Civilization IV Complete, there should be multiple Play buttons (for example "Play vanilla", "Play Warlords" and "Play Beyond the Sword") underneath each other.

As for implementation, I guess it would make sense to make it possible to let game be a list? And then another idea would be to make multiple 'types', such as primary and alternate, for determining where in the UI the different games will be put.

**Comment by strycore** [comment]
Documentation for the feature: https://github.com/lutris/lutris/commit/bd92a295a77484c2ea1f6ef6140d25057f24965a

**Comment by jdamboeck** [comment]
Is it possible to add them later if it is not in the installer?

**Comment by danieljohnson2** [comment]
You can edit the .yml files in ~/.config/lutris/games.

Here's what the start of my 'Batman - Arkham Asylum' configuration looks like (there's more after):
```yml
game:
  exe: /home/danj/Games/gog/batman-arkham-asylum-game-of-the-year-edition/drive_c/GOG
    Games/Batman Arkham Asylum GOTY/Binaries/BmLauncher.exe
  launch_configs:
  - exe: /home/danj/Games/gog/batman-arkham-asylum-game-of-the-year-edition/drive_c/GOG
      Games/Batman Arkham Asylum GOTY/Binaries/ShippingPC-BmGame.exe
    name: GameTask
    working_dir: /home/danj/Games/gog/batman-arkham-asylum-game-of-the-year-edition/drive_c/GOG
      Games/Batman Arkham Asylum GOTY/Binaries
  name: Batman Arkham Asylum GOTY
  working_dir: /home/danj/Games/gog/batman-arkham-asylum-game-of-the-year-edition/drive_c/GOG
    Games/Batman Arkham Asylum GOTY/Binaries
```
This shows the launch_config for the "GameTask", which bypasses the launcher and it's configuration window and goes right to the game.

I've been working on this, fixing bugs with the way working_dir works here. You need at least 0.5.12 to use one in a launch-config, and you should specify a full path, not a relative one, if you want it to work in 0.5.12.
