### ISSUE TITLE
working_dir for installer scripts

### ISSUE THREAD

**Issue by rienafairefr** [lutris/lutris#6155]
Hi to all,

I wanted to setup a few "local install scripts" so that I can offer reproducible "easy install scripts" for non-tech-literate people, on a few linux machines.

I already can mount a remote folder (from my NAS) containing installers, I can write the installation scripts yaml, mostly, the only nag I found is that when I run "lutris install -i script.yml", there is apparently no way to specify to a "wineexec" step an executable that is _right there_ in the same folder as the installer script yaml. I have to specify the full absolute path on the mounted folder, which is not super "portable".
Maybe there is a way that I didn't see, maybe I completely misunderstood the point of these local install scripts. 

A workaroung would probably by a "copy-then-install", where the setup files are copied to the game prefix path, then executed there. But I couldn't make it work either (the src is also not relative to the install script). 

I'm tempted to send a pull request for a variable a bit like $GAMEDIR that could provide that functionality (like, idk, $INSTALLSCRIPTDIR), but before that I'm interested in your point of views on that working_dir (it is actually by default set to the wine prefix, so has no notion of that install script directory)

**Comment by danieljohnson2** [comment]
Your proposed ``$INSTALLSCRIPTDIR`` has really nothing to do with the ``working_dir``. The ``working_dir`` is the current directory we set before starting the game when you play it; it is not he current directory of Lutris itself; because we change that on the fly, we can't trust it.

I'd say go for the PR.

**Comment by rienafairefr** [comment]
Right, thanks, there are two places with a working_dir, one for the game, and one for the winexec steps, here's an example/prototype
```
game_slug: nice-game
slug: nice-game
name: Nice Game
runner: wine
version: 1.0.0
script:
  game:
    arch: win32
    exe: $GAMEDIR/drive_c/Games/Game/Launcher.exe
    prefix: $GAMEDIR
    working_dir: $GAMEDIR/drive_c/Games/Game # I'm not talking about this one 
  installer:
    - task:
        name: create_prefix
        prefix: $GAMEDIR   
    - task:
        executable: setup.exe
        working_dir: /mnt/installers/nice-game # I'm talking about this one
        name: wineexec
        prefix: $GAMEDIR
```
If the /mnt/installers/nice-game could be `$INSTALLSCRIPTDIR` that'd be a "portable YML installer"
