### ISSUE TITLE
File variable not being updated when using $-notation

### ISSUE THREAD

**Issue by FakeShemp** [lutris/lutris#661]
If you write an install script with for instance a `merge` directive, like the one below...

```yaml
files:
- file1: N/A:Please select file
game:
  main_file: file1
installer:
- merge:
    dst: $GAMEDIR
    src: file1
```
the `main_file` will get updated to link to the copied file in `$GAMEDIR`, like it should.

However, if you use a $-notation in front of `file1` in the `merge` part, like below...

```yaml
files:
- file1: N/A:Please select file
game:
  main_file: file1
installer:
- merge:
    dst: $GAMEDIR
    src: $file1
```
the game will install fine, but the `main_file` will not get updated and instead will link to the original file at the source location, and not the copied one.
