### ISSUE TITLE
Winesteam/Wine runner problems

### ISSUE THREAD

**Issue by soredake** [lutris/lutris#680]
Latest lutris from master, gentoo amd64.

# Problem №1 (winesteam runner):
`$GAMEDIR` is unset (set to default `None`) for no reason and this causing any wine commands such as creating prefix and settings registry to fail.
[collapselog.zip](https://github.com/lutris/lutris/files/1450342/collapselog.zip)
`collapse.yaml`:
```
name: Collapse
game_slug: collapse1
version: Steam
slug: collapse1-steam
runner: winesteam

script:
  game:
    appid: 289620
    prefix: $GAMEDIR/prefix
  installer:
  - task:
      name: create_prefix
      prefix: $GAMEDIR/prefix
  - task:
      name: set_regedit
      prefix: $GAMEDIR/prefix
      path: HKEY_CURRENT_USER\Software\Wine\DllRedirects
      key: wined3d
      value: wined3d-csmt.dll
      type: REG_SZ
```

# Problem №2 (wine runner):
`detect_prefix_arch` function is always returns `win32` and wine commands fails in `win64` prefix unless i specify `arch: win64` in every task.
[twd3log.zip](https://github.com/lutris/lutris/files/1450288/twd3log.zip)
`twd3.yaml`:
```
name: twd3
game_slug: twd3
version: Wine
slug: twd3-64bit
runner: wine

script:
  files:
  - installer: "N/A:Select the game's setup file"
  game:
    exec: drive_c/Game/game.exe
    prefix: $GAMEDIR/prefix
  installer:
  - task:
      description: Setting up wine prefix
      name: create_prefix
      prefix: $GAMEDIR/prefix
      arch: win64
  - task:
      description: 'Installing twd3

      Make sure to close installer after installation finishes

      After exiting, wait a bit for lutris to finish'
      executable: $installer
      name: wineexec
      prefix: $GAMEDIR/prefix
  - task:
      name: set_regedit
      prefix: $GAMEDIR/prefix
      path: HKEY_CURRENT_USER\Software\Wine\DllRedirects
      key: wined3d
      value: wined3d-csmt.dll
      type: REG_SZ
```

@strycore @daniel-j
