### ISSUE TITLE
Allow a referer link for downloads

### ISSUE THREAD

**Issue by Lucki** [lutris/lutris#697]
Some sites needs a referer link set to be able to download game files.
`wget http://site.com/url-that-doesnt-resolve-to-a-proper-filename --referer=www.mywebsite.com -o actual_local_filename.zip`
```
- file3:
    url: http://site.com/url-that-doesnt-resolve-to-a-proper-filename
    filename: actual_local_filename.zip
    referer: www.mywebsite.com
```
