### ISSUE TITLE
Give users option to install raw script

### ISSUE THREAD

**Issue by rendeko** [lutris/lutris#712]
https://forums.lutris.net/t/local-script-wants-runner-specified/1296

When installing through "lutris -i ~/script.yml", Lutris reports back`Missing field “runner” in install script`. I cannot find any use of `runner: "wine"` or similar online. I have tested this with my own scripts, as well as the Overwatch script. Defining a wine version through `wine: version: ` does not solve this.

**Comment by strycore** [comment]
You're using the wrong script format. Why would the installer default to wine? that makes no sense at all

**Comment by strycore** [comment]
- Let users install incomplete scripts by auto-detecting if the script has a script section
- For raw scripts, show a form on the installer with metadata fields such as game name and runner

**Comment by rendeko** [comment]
What would be the right script format, json?

**Comment by strycore** [comment]
No, that shouldn't matter (yaml or json). What does matter is that the script you can edit on the website is not the whole thing. It's contained in another document under a `script` section. This document also has other fields such as name or runner. When you open the "view script" link on the website, there is a link that will bring you to the full script.

The plan here is to let everyone install raw script (with just the `script` section) and prompt for all missing information.

**Comment by TomJansen** [comment]
@strycore even when downloading the full script, the error `Missing field “runner” in install script` persists.

**Comment by liuseemin** [comment]
@TomJansen @rendeko 
Go check [docs/installers.rst](https://github.com/lutris/lutris/blob/master/docs/installers.rst#trying-the-installer-locally)

change "runner: Linux" to "runner: wine", that works.
except for the script, you need to specify name, runner, version..etc, like the example do.

**Comment by rendeko** [comment]
Just curious if there's any progress on allowing users to install raw scripts? Or perhaps if there's a way to create a full script without going through the Lutris website submission?

**Comment by liuseemin** [comment]
Installation with raw script works just fine.
I've installed programs several times successfully.
As I mentioned before, just follow the example in docs.

**Comment by strycore** [comment]
The installation of local scripts doesn't work well because I absolutely never use them (and probably never will) but no one else wants to maintain that feature either. I'll  see what I can do to improve the situation for the 0.4.15 release.

**Comment by nonchip** [comment]
downloaded a functioning raw script (NOT just the editable section), which contains `"runner":"wine"`, ran it with `lutris -i`, "missing field: runner" and an empty "please select version to install" box pop up. also the process of `lutris -i` sticks around after closing all of them and ignores `^C`, can only be sigKILLed.

then I removed what looks like a paginated search result, (the outer object and array, just leaving the inner object which actually contains all the info), and this worked perfectly. so apparently the API just wraps it into some query-result-metadata that prevents it from doing what it's supposed to ("To install the game, download the full script.")

**Comment by liuseemin** [comment]
I suggest you provide _full_ scripts on the lutris website.
People are confused because it says "install script", which's obviously not enough for achieving the actual installation.

For those who still fail to install through script, here's the example script from [docs/installers.rst](https://github.com/lutris/lutris/blob/master/docs/installers.rst#trying-the-installer-locally)
```
name: My Game
game_slug: my-game
version: Installer
slug: my-game-installer
runner: wine

script:
  game:
    exe: $GAMEDIR/mygame
    args: --some-args
    prefix: $GAMEDIR/prefix
    arch: win64
    working_dir: $GAMEDIR/prefix
  files:
  - installer: "N/A:Select the game's setup file"
  installer:
  - task:
    executable: installer
    name: wineexec
    prefix: $GAMEDIR/prefix
    arch: win64
  wine:
    Desktop: true
    WineDesktop: 1024x768
    overrides:
      ddraw.dll: n
  system:
    terminal: true
    env:
      WINEDLLOVERRIDES: d3d11=
      SOMEENV: true
```
The script part is what you can actually see on the website by clicking `View install script`
So you can actually replace that part with the scrpit of whatever app you want to try to customize the installation. (I never tried downloading json, but I guess it just works better with yml)

Name this file to `whateveryouwant.yml`
To run this script: `lutris -i /path/to/whateveryouwant.yml`
