### ISSUE TITLE
Dotnet fails to be installed using Lutris installation scripts.

### ISSUE THREAD

**Issue by Zeioth** [lutris/lutris#841]
Hi, i'm working on this installer. And everything works fine except dotnet45. At some point during the installation, it enters on infinite loop.

The problematic block of code is this one (If I delete it, the installation is completed correctly):

    - task:
        app: dotnet45
        name: winetricks
        prefix: $GAMEDIR/prefix

My entire installation script. The game is "[Killer is Dead](https://lutris.net/games/killer-is-dead/)"

```
files:
- vk9: https://raw.githubusercontent.com/Zeioth/zeioth-lutris/master/game-installers/killer-is-dead/vk9-0.25.0.zip
- unlockfps: https://raw.githubusercontent.com/Zeioth/zeioth-lutris/master/game-installers/killer-is-dead/kid-unlockfps-0.0.1.zip
game:
  appid: 261110
installer:
- task:
    name: create_prefix
    prefix: $GAMEDIR/prefix
- task:
    app: dotnet45
    name: winetricks
    prefix: $GAMEDIR/prefix
- task:
    app: xact_jun2010
    name: winetricks
    prefix: $GAMEDIR/prefix
- extract:
    dst: $GAMEDIR/Binaries/Win32/
    file: vk9
    format: zip
- extract:
    dst: $GAMEDIR/KidGame/Config/
    file: unlockfps
    format: zip
winesteam:
  version: staging-3.6-i386
```
You can see the errors in the [installation.log](https://github.com/lutris/lutris/files/1958271/installation.log).
