### ISSUE TITLE
Lutris ignores 'arch: win32' in installer when building prefix for Steam Wine

### ISSUE THREAD

**Issue by CitrusAlex** [lutris/lutris#919]
I've tried to install a game (https://lutris.net/games/the-sims-3 but I added 32 bit arch) using Steam Wine runner with an installer that specifies that it needs its own 32 bit prefix by
`  arch: win32
  prefix: $GAMEDIR/prefix`
When the game has finished download and installation, it fails to launch. Since default Steam Wine arch is 64 bit, I assume I just need to stop this steam session for Lutris to launch the game using 32 bit prefix. I close steam and try to play the game. It fails. I run `lutris -d` and I see this
`wine: WINEARCH set to win32 but '/home/alex/.local/share/lutris/runners/winesteam/prefix64/drive_c/Program Files (x86)/Steam/steamapps/common/The Sims 3/prefix' is a 64-bit installation.
`
I open that prefix and see that the prefix has two Program Files folders and one is x86 one, so it's a 64 bit one. The game that I am trying to play needs 32 bit prefix to run. 
Please fix?

**Comment by daniel-j** [comment]
Please show us your installer script.

**Comment by strycore** [comment]
Created a test installer here: https://lutris.net/games/test/ and ran the installer. 32bit prefix created with no problem.

Make sure that a 64bit prefix does not already exist in the game folder.

**Comment by CitrusAlex** [comment]
Since I moved back to Ubuntu distro, I can’t reproduce how wine creates win64 prefix inside game folder either, but I can still reproduce how Steam runs the game inside its winesteam prefix, prefix64, and not game’s 32 bit prefix.

**Comment by daniel-j** [comment]
> I can still reproduce how Steam runs the game inside its winesteam prefix, prefix64, and not game’s 32 bit prefix.

Show us the terminal output when you run the game.

**Comment by CitrusAlex** [comment]
Turnes out it was due to another problem which would give an error that was identical to the error that The Sims 3 would give if was launched inside 64 bit prefix. Please excuse for not figuring out sooner. Closed.

**Comment by bjoern-tantau** [comment]
Can we reopen this issue? I have the same error, when trying to run Batman: Arkham Asylum. I used the following installer:

```
game:
  appid: 35140
  arch: win32
  prefix: $GAMEDIR/prefix
installer:
- task:
    arch: win32
    name: create_prefix
- task:
    app: winxp dotnet20 dotnet35 physx mdx d3dx9 d3dcompiler_43
    arch: win32
    description: Installing various winetricks. This might take a while....
    name: winetricks
    prefix: $GAMEDIR/prefix
    silent: false
winesteam:
  esync: 'true'
  version: staging-3.16-i386
```

It always installs into `~/.local/share/lutris/runners/winesteam/prefix64` instead of `~/.local/share/lutris/runners/winesteam/prefix`.
