### ISSUE TITLE
"write_file" task crashing

### ISSUE THREAD

**Issue by basxto** [lutris/lutris#935]
When I use the example from the [docs](https://github.com/lutris/lutris/blob/master/docs/installers.rst), I just get `TypeError("argument of type 'NoneType' is not iterable",)`
```
name: Bionic Dues
game_slug: bionic-dues
version: Humble
slug: bionic-dues-humble
runner: linux

script:
  files:
  - BionicDuesLin.zip: N/A:Select the game's zip file
  game:
    exe: start.sh
  installer:
  - extract:
    file: BionicDuesLin.zip
  - write_file:
    file: $GAMEDIR/myfile.txt
    content: 'This is the contents of the file.'
```
I planned on writing a script for starting the correct binary for the platform, but didn’t get it working.

Lutris 0.4.18 on ArchLinux

**Comment by basxto** [comment]
not related to write_file

**Comment by stendler** [comment]
I've had the same error with `extract`. Just to document how I resolved it:

Check the indentation of the options of the directive:

Failing script:
```yml
   - extract:
     file: "file"
     dst: "$GAMEDIR/drive_c/Program Files/"
     format: zip
```

Fixed:
```yml
   - extract:
       file: "file"
       dst: "$GAMEDIR/drive_c/Program Files/"
       format: zip
```

Note the additional spaces in front of `file`, `dst` and `format`.
