### ISSUE TITLE
[IDEA] Add "launcher options" for games

### ISSUE THREAD

**Issue by duhow** [lutris/lutris#984]
Add a section in `scripts` in order to open another EXE (config.exe for changing game resolutions or other stuff), or open a URL (register, status).
```yaml
launcher:
  - config:
        exe: '$GAMEDIR/drive_c/Program Files (x86)/PlayOnline/SquareEnix/FINAL FANTASY XI/ToolsEU/FINAL FANTASY XI Config.exe'
        prefix: $GAMEDIR
        name: 'Configure'
  - register:
        url: http://www.playonline.com/homeeu/polshift/
        name: 'Register account'
```
